[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
  "@chainlink/=lib/chainlink-brownie-contracts/",
  "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
  "forge-std/=lib/forge-std/src/",
  "@aave-v3-core/=lib/aave-v3-core/contracts/",
  "@yield-advance/=lib/yield-advance/contracts",
  '@token-registry/=lib/token-registry/src',
]



